import { IHttpErrorPayload } from "@fpx/core"

export interface  Basecurrencycasa {
       accountNumber:string, 
       accountName:string, 
       accountCurrency:string, 
       accountType:string, 
       accountNickname:string, 
       unclearedBalance:number, 
       availableBalance:number, 
       closingBalance:number, 
       currentBalance:number, 
       lienAmount:number, 
       creditInterestFrequency:string, 
       creditInterestRate:number, 
       ledgerAmount:number, 
       creditNetInterestAccrued:number, 
       floatBalance:number, 
       holdBalance:number, 
       actualBalance:number, 
       taxRegistrationNumber:string, 
       email:string, 
       mobileNumber:string, 
       BICCode:string, 
       productCode:string, 
       productDesc:string, 
       address:string, 
       statementFrequency:string, 
       nomineeDetails:string, 
       mailingAddress:string, 
       addressInfo:any, 
       accountStatus:string, 
       nickName:string, 
       branchCode:string, 
       branchDesc:string, 
       customerCode:string, 
       closeDate:string, 
       accountTypeDesc:string, 
       countryName:string, 
       openDate:string, 
       routingCode:string, 
       iban:string, 
       openingBalance:number 
  }
  
 
