export interface Multibillrequest {
        totalBillAmount:number, 
        debitAccount:string, 
        chargesCurrency:Currency, 
        termsFlag:string, 
        accountType:string, 
        rateApplied:number, 
        customerCode:string, 
        chargesAmount:number, 
        authOn:string, 
        tranRef:string, 
        createdOn:string, 
        baseCurrencyAmount:number, 
        authBy:string, 
        modifiedOn:string, 
        baseRateApplied:number, 
        createdBy:string, 
        modifiedBy:string, 
        paymentDate:string, 
        multibillrequestdetail:Multibillrequestdetail[], 
        remarks:string, 
        status:string, 
  }
  
