import { IHttpErrorPayload } from "@fpx/core"

export interface  Eligibletoaccount {
       preferredAccount:boolean,
       id?: string;
       tenantId:string, 
       accountNumber:string, 
       accountName:string, 
       accountSecondName:string, 
       accountCurrency:string, 
       accountType:string, 
       accountNickname:string, 
       availableBalance:number, 
       unclearedBalance:number, 
       closingBalance:number, 
       currentBalance:number, 
       lienAmount:number, 
       creditInterestFrequency:string, 
       creditInterestRate:number, 
       ledgerAmount:number, 
       signerStatus:string, 
       creditNetInterestAccrued:number, 
       actualBalance:number, 
       floatBalance:number, 
       holdBalance:number, 
       email:string, 
       mobileNumber:string, 
       addressInfo:any, 
       mailingAddress:string, 
       address:string, 
       taxRegistrationNumber:string, 
       statementFrequency:string, 
       nomineeDetails:string, 
       productDesc:string, 
       BICCode:string, 
       productCode:string, 
       lineOfCreditAmount:number, 
       availableFunds:number, 
       nickName:string, 
       openingBalance:number, 
       accountStatus:string, 
       branchCode:string, 
       branchDesc:string, 
       openDate:string, 
       closeDate:string, 
       customerCode:string, 
       countryName:string, 
       accountTypeDesc:string, 
       relationshipNumber:string, 
       iban:string, 
       routingCode:string, 
       transitNumber:string, 
       institutionNumber:string, 
       ownership:string, 
       lineOfCreditInterestRate:string, 
       currentInterestRate:string, 
       bankName:string, 
       paymentDueDate:string, 
       atmLimit:string, 
       posLimit:string, 
       baseCurrencyAvlBal:number, 
       baseCurrencyCurrentBal:number 
  }
  
 
