apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "igcb-cbxr-ui-retail.fullname" . }}
  labels:
    app: {{ template "igcb-cbxr-ui-retail.name" . }}
    chart: {{ template "igcb-cbxr-ui-retail.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ template "igcb-cbxr-ui-retail.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "igcb-cbxr-ui-retail.name" . }}
        release: {{ .Release.Name }}
    spec:
      securityContext:
         fsGroup: 101
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          env:
            - name: baseURL
              value: "{{ .Values.config.baseURL }}"
            - name: contextPath
              value: "{{ .Values.config.contextPath }}"
            - name: commonPublisher
              value: "{{ .Values.config.commonPublisher }}"
            - name: accountsPublisher
              value: "{{ .Values.config.accountsPublisher }}"
            - name: customersPublisher
              value: "{{ .Values.config.customersPublisher }}"
            - name: cardsPublisher
              value: "{{ .Values.config.cardsPublisher }}"
            - name: depositsPublisher
              value: "{{ .Values.config.depositsPublisher }}"
            - name: defaultPublisher
              value: "{{ .Values.config.defaultPublisher }}"
            - name: workflowPublisher
              value: "{{ .Values.config.workflowPublisher }}"
            - name: iamPublisher
              value: "{{ .Values.config.iamPublisher }}"
            - name: transfersPublisher
              value: "{{ .Values.config.transfersPublisher }}"
            - name: loansPublisher
              value: "{{ .Values.config.loansPublisher }}"
            - name: billPaymentsPublisher
              value: "{{ .Values.config.billPaymentsPublisher }}"
          resources:
            requests:
              memory: "{{ .Values.resources.requests.memory }}"
              cpu: "{{ .Values.resources.requests.cpu }}"
            limits:
              memory: "{{ .Values.resources.limits.memory }}"
              cpu: "{{ .Values.resources.limits.cpu }}"
          volumeMounts:
            - name: configjson
              mountPath: {{ .Values.config.configJsonPath }}
      volumes:
        - name: configjson
          configMap:
            name: sitretailconfigmap  
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      imagePullSecrets:
        - name: {{ .Values.dockerRegSecret }}

